#!/bin/bash
/Library/Frameworks/R.framework/Resources/bin/Rscript eQTL_plotting.R cut_genotype_data_all_treated_final.tsv_matched.tsv_MatrixEQTL_loose_p5_1MB.cis cut_genotype_data_all_treated_final.tsv_matched.tsv cut_GEx_treated_4000_and_2000.tsv_matched.tsv rs4236435 ILMN_1651819

/Library/Frameworks/R.framework/Resources/bin/Rscript eQTL_plotting.R cut_genotype_data_all_treated_baseline.tsv_matched.tsv_MatrixEQTL_loose_p5_1MB.cis cut_genotype_data_all_treated_baseline.tsv_matched.tsv cut_GEx_baseline_4000_and_2000.tsv_matched.tsv rs4236435 ILMN_1651819

/Library/Frameworks/R.framework/Resources/bin/Rscript eQTL_plotting.R cut_genotype_data_all_treated_final.tsv_matched.tsv_MatrixEQTL_loose_p5_1MB.cis cut_genotype_data_all_treated_final.tsv_matched.tsv cut_GEx_treated_4000_and_2000.tsv_matched.tsv rs2835314 ILMN_1652237

/Library/Frameworks/R.framework/Resources/bin/Rscript eQTL_plotting.R cut_genotype_data_all_treated_baseline.tsv_matched.tsv_MatrixEQTL_loose_p5_1MB.cis cut_genotype_data_all_treated_baseline.tsv_matched.tsv cut_GEx_baseline_4000_and_2000.tsv_matched.tsv rs2835314 ILMN_1652237

/Library/Frameworks/R.framework/Resources/bin/Rscript eQTL_plotting.R cut_genotype_data_all_treated_final.tsv_matched.tsv_MatrixEQTL_loose_p5_1MB.cis cut_genotype_data_all_treated_final.tsv_matched.tsv cut_GEx_treated_4000_and_2000.tsv_matched.tsv rs2015901 ILMN_1652594

/Library/Frameworks/R.framework/Resources/bin/Rscript eQTL_plotting.R cut_genotype_data_all_treated_baseline.tsv_matched.tsv_MatrixEQTL_loose_p5_1MB.cis cut_genotype_data_all_treated_baseline.tsv_matched.tsv cut_GEx_baseline_4000_and_2000.tsv_matched.tsv rs2015901 ILMN_1652594

